# version: "1"
services:
    podepshtml:
      build:
        context: .
        dockerfile: ./pode/dockerfile
      ports:
        - "8080:8080"
      container_name: pode-pshtml
      hostname: pode
      environment:
        TZ: "Europe/Zurich"
