# **************************************************************************************************************************
# Buidl images:  docker-compose build --build-arg now="$(date +%Y-%m-%d)" --build-arg version="1.0.0"
# Run container: docker run -e TZ="Europe/Zurich" --hostname alma --name alma --network custom -it linux-alma
# Run container: docker run -e TZ="Europe/Zurich" --hostname alpine --name alpine --network custom -it linux-alpine
# **************************************************************************************************************************
include:
  - alma.yml
  - alpine.yml
  
services:
  nexus:
    image: sonatype/nexus3:latest
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    env_file:
    - path: ./default.env

volumes:
  nexus-data: {}